language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-1_Mityagina_AllLabs
  - make -j
  - ./vector/vector
  - ./VectorTest/VectorTest
  - ./Matrix/Matrix
  - ./MatrixTest/MatrixTest
  - ./Stack/Stack
  - ./StackTest/StackTest
notifications:
  email: false
