language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-1_Mityagina_AllLabs
  - make -j
  ##- ./StackTest/StackTest
  ##- ./QueueTest/QueueTest
  - ./PolinomialTest/PolinomialTest
  - ./MonomialTest/MonomialTest
notifications:
  email: false
