language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-1_Mityagina_AllLabs
  - make -j
  - ./Stack/Stack
  - ./Queue/Queue
  - cd ./QueueTest/
notifications:
  email: false
