language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-1_Mityagina_AllLabs
  - make -j
  - ./Queue/Queue
  - ./QueueTest/QueueTest
notifications:
  email: false
