language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-1_Mityagina_AllLabs
  - make -j
  - ./ViewTableTest/ViewTableTest
  - ./VectorTest/VectorTest
  - ./MatrixTest/MatrixTest
  - ./ArrayListTests/ArrayListTests
  - ./ListTests/ListTests
  - ./mStackTest/mStackTest
  - ./MonomialTest/MonomialTest
  - ./PolandTest/PolandTest
  - ./PolinomialTest/PolinomialTest
  - ./QueueTest/QueueTest
  - ./StackTest/StackTest
  - ./StackListTest/StackListTest
notifications:
  email: false
